### ISSUE TITLE
Controller is still controlling Big Picture menu while I'm playing 

### ISSUE THREAD

**Issue by DocMAX** [Samsagax/gamescope-session#14]
I get a problem like in https://www.reddit.com/r/Steam/comments/aflu4a/controller_is_still_controlling_big_picture_menu/.
I don't have the problem if it run gamescope directly (gamescope -e -- steam -tenfoot).
what could be the cause?

**Comment by DocMAX** [comment]
Edit: Also steam overlay doesn't work

**Comment by DocMAX** [comment]
Found the problem: export STEAM_MULTIPLE_XWAYLANDS=1
Seems not to be compatible with Big Screen?

**Comment by Samsagax** [comment]
This session used to work fine with BPM but didnt had all those environment variables. Try to set them off in a conf file under `~/.config/environment.d/` and test.

Btw. The standard session comes with GamepadUI enabled by default. Didn't that one work for you?

**Comment by Samsagax** [comment]
Is this issue still relevant?
