### ISSUE TITLE
Hello I have a problem with the gamescope service and a black screen

### ISSUE THREAD

**Issue by pachof** [Samsagax/gamescope-session#16]
My computer is an AMD E1-6010 APU with AMD Radeon R2 Graphics with two cores and I have forced amdgpu driver and when I put the gamescope service I get an error "Failed to enable unit: File display-manager.service: Invalid cross-device link"
good but when I start it it doesn't work it stays black

**Comment by Samsagax** [comment]
Do you have the radv Vulkan driver? What does `~/.gamescope-stdout.log` says?

**Comment by Samsagax** [comment]
@pachof any news on this one?

**Comment by pachof** [comment]
oh hi sorry for no responds

**Comment by pachof** [comment]
i use amdvlk and vulkan-radeon

**Comment by pachof** [comment]
i use radv

**Comment by pachof** [comment]
this is what appears

wlserver: [backend/headless/backend.c:82] Creating headless backend
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV KABINI': queue family 1
vulkan: physical device does not support DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [xwayland/server.c:92] Starting Xwayland on :2
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55dc387458f0 (res 0x55dc387c66f0)
wlserver: [xwayland/server.c:250] Xserver is ready
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55dc384bad30 (res 0x55dc38770060)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 33
pipewire: renegotiating stream params (size: 1280x720)
gamescope: received kill signal, terminating!
(EE) failed to read Wayland events: Broken pipe
(EE) failed to read Wayland events: Broken pipe

**Comment by pachof** [comment]
gamescope works normaly

**Comment by pachof** [comment]
Right now I run it with gdm and this appeared

wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV KABINI': queue family 1
vulkan: physical device does not support DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
wlserver: [libseat] [libseat/backend/logind.c:137] Could not take device: Device or resource busy
wlserver: [backend/session/session.c:322] Failed to open device: '/dev/dri/card0': Resource temporarily unavailable
drm: Could not open KMS device
Failed to initialize output

**Comment by Samsagax** [comment]
Hello. I got confused on the events. The original issue is still present? Have you tried recent changes? What is your hardware and graphics stack?

**Comment by pachof** [comment]
hello i use libdrm-amdgpu my problem is still

2022-09-19 13:52 GMT-05:00, Joaquín Ignacio Aramendía
***@***.***>:

**Comment by pachof** [comment]
Sorry, but I do not understand
 What do you mean
 about hardware and the graphics stack.

2022-09-22 13:25 GMT-05:00, EL Pacho ***@***.***>:

**Comment by Samsagax** [comment]
What GPU do you have? And what version of kernel, mesa, and Vulkan drivers you have installed?

**Comment by pachof** [comment]
i have radeon r2, my kernel is 5.19.10-zen1-1-zen, my driver vercion is xf86-video-amdgpu 22.0.0-1 lib32-amdvlk 2022.Q3.4-1 amdvlk 2022.Q3.4-1 and my mesa vercion is mesa 22.1.7-1

**Comment by Samsagax** [comment]
You should remove amdvlk and use vulkan-radeon (radv driver). Amdvlk doesn't support many features needed for gamescope.

**Comment by pachof** [comment]
no works
wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to
socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to
open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
ATTENTION: default value of option vk_xwayland_wait_ready overridden
by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV KABINI'
vulkan: physical device does not support DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
drm: drmSetClientCap(ATOMIC) failed
Failed to initialize output

2022-09-25 8:23 GMT-05:00, Joaquín Ignacio Aramendía ***@***.***>:

**Comment by pachof** [comment]
my gpu is a radeon r2 normally it works with radeon but since it has
the GCN 1.1 architecture it lets me force the amdgpu drivers

2022-09-27 20:44 GMT-05:00, Joaquín Ignacio Aramendía
***@***.***>:

**Comment by Samsagax** [comment]
You need to force AMDgpu drivers and also set `R600_DEBUG=nodcc` globally on your environment. (For this session you can set it in a `~/.config/environment.d/*.conf` file). Otherwise it won't work.

**Comment by pachof** [comment]
no works 
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV KABINI': queue family 1
vulkan: physical device does not support DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
drm: drmSetClientCap(ATOMIC) failed
Failed to initialize output

**Comment by Samsagax** [comment]
I think your GPU is not supported since it doesn't support DRM modifiers.
