### ISSUE TITLE
Failed to enable unit: File display-manager.service: Invalid cross-device link

### ISSUE THREAD

**Issue by fredinj** [Samsagax/gamescope-session#18]
I'm on Endeavour OS

I installed this from aur, but everytime I tried to enable the service with `systemctl enable gamescope@<user>.service` it kept giving me the error `Failed to enable unit: File display-manager.service: Invalid cross-device link`. I had made sure that sddm was disabled and there were no other active display managers.

This is how I got it to work:

Commented out the line `Alias=display-manager.service` in `/etc/systemd/system/gamescope@.service`
Enabled the service using `systemctl enable gamescope@<user>.service`
Manually made the symlink `display-manager.service` to `/etc/systemd/system/gamescope@.service`
Uncommented the line `Alias=display-manager.service`  in `/etc/systemd/system/gamescope@.service`

I'm not sure if this helps anyone

**Comment by kutlaykizil** [comment]
I was having the same issue on my Arch install (also installed from AUR), what I did was to manually enter the username in _gamescope@<user>.service_ and change its name to _gamescope.service_ and then start the service.

**Comment by Samsagax** [comment]
The service is no longer called directly
