### ISSUE TITLE
No shutdown when clicking on shutdown in gamepadui

### ISSUE THREAD

**Issue by eduard-hdt** [Samsagax/gamescope-session#22]
Hi, I wonder if I am missing something but when I try to shutdown I just get kicked to lightdm.
I have set lightdm to autologin into the gamescope-session.

Another thing that might be just a thing of some config is the switch to desktop button which does nothing for me and maybe there's a way I could change that.

**Comment by eduard-hdt** [comment]
Ok, when I log back in to the session the shutdown gets finished...
Can I fix that somehow?

**Comment by Samsagax** [comment]
> Ok, when I log back in to the session the shutdown gets finished... Can I fix that somehow?

That would depend on Valve to fix. They even added this comment to the session since the client seems to be misbehaving:
```
# Workaround for steam getting killed immediatly during reboot
export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
	reboot
fi

# Workaround for steam getting killed immediatly during shutdown
# Same idea as reboot sentinel above
export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
	poweroff
fi
```
You won't notice that behaviour if using lightdm with autologin but if you enter it by normal greeter login will seem wonky. I'll investigate further to try and see if those sentinel catches can be reversed.

**Comment by Samsagax** [comment]
I think I fixed it with this: https://github.com/Samsagax/gamescope-session/commit/c45dc1367fdd05bf57c9775d25e373dbb52f1aa2

Please retest.

**Comment by eduard-hdt** [comment]
yes, works great now. Thanks!
