### ISSUE TITLE
Text appearing over gamescope session.

### ISSUE THREAD

**Issue by Mrpuppyz** [Samsagax/gamescope-session#7]
So I have an issue with some text showing up on my gamescope session. (Running holoiso build) It is not present when a game is started and doesn't show up on desktop mode. I think the text showed up when I enabled a wwan card for Internet. This PC has a Reyzen 5700x and a RX 6700. Any recommendations I can try to get this text to go away? 

![20220525_161758.jpg](https://user-images.githubusercontent.com/103858972/170536989-40f90085-d4a6-4f10-8fd0-69ec3e3c124d.jpg)![20220525_161805.jpg](https://user-images.githubusercontent.com/103858972/170536994-ff76da60-e396-447c-9f18-c98b9475155c.jpg)![20220525_161813.jpg](https://user-images.githubusercontent.com/103858972/170537003-a6db23a5-f2a6-4dfb-803c-9a904f5474ef.jpg)![20220525_161817.jpg](https://user-images.githubusercontent.com/103858972/170537012-5e027da0-cf88-4b8d-a630-a8a18afd6a58.jpg)

**Comment by Samsagax** [comment]
Are you using the session of Bolo iso? They use their own session script that doesn't come from us.

**Comment by Mrpuppyz** [comment]
I am on the Holoiso build

**Comment by Samsagax** [comment]
> I am on the Holoiso build

Seems to me is a client issue. More specifically the Plugin Manager might be erroring out the quick access menu (where the battery is present).

HoloISO doesn't use this project, uses Valve session which is not the same (though inspiration was taken from there). I don't think I can help you with this, should report to HoloISO's developers.
